### ISSUE TITLE
Do we really have to pass document everywhere?

### ISSUE THREAD

**Issue by domenic** [domenic/element-constructors#1]
The only alternate strategy I could hope for would be that you can derive it from the global on which `Element` sits.

However, given that globals (windows) are many-to-many with documents, this seems unlikely to work.

Someone with more understanding of existing implementations and the edge-cases around that could probably give a more definitive answer.

**Comment by bzbarsky** [comment]
I think it would be fine to default to the document of the global but allow passing in a different one.

Given things like responseXML which are not hanging off a Window, we do need the option of passing in a document of our choice...

**Comment by annevk** [comment]
We get it from the global for `new Document()`, `new Text()`, etc.

**Comment by bzbarsky** [comment]
new Document is fine.  We're going to need a document argument for new Text if we want to explain creation of textnodes in XHR responseXML via the ctor.

**Comment by domenic** [comment]
From the thread, @bzbarsky said:

> It's necessary, but I think the document should be allowed, but not required.  As in, the signature should be:
> 
>   new Element(localName, namespace, prefix, document).
> 
> (though maybe prefix should come after document; hard to say).  If the document is undefined, then we get a document as follows: Element is a function, so has an associated Realm.  This Realm's [[globalThis]] is a Window.  This Window has a .document; use that.
> 
> The only reason we need the ability to specify a document at all is that there are documents around that are not inside a browsing context (XHR responseXML, for example) and we need to be able to create elements that have those documents as an ownerDocument.  But those document's don't have their own global/Realm and hence don't have separate instances of the Element constructor.

And that of course makes sense. I like document last. Will update to do that.

I _think_ that you can express the scheme you gave in ES as

``` js
constructor(..., document = window.document) { }
```

modulo the usual what-if-someone-modified-`window.window` or `window.window.document` concerns. Although maybe window vs. windowproxy confuses things. Not that it really matters; I'm just wanting to figure out what to write in the `.js` file that isn't too misleading.

**Comment by bzbarsky** [comment]
> I think that you can express the scheme you gave in ES as

Yeah, modulo windowproxy issues I think that works.

The `window` and `document` attributes on the `Window` interface are unforgeable, so you don't have to worry about them being modified.  If you use `doc = document` you can even avoid the windowproxy concerns, I think.

**Comment by domenic** [comment]
I went for explicit (`GetFunctionRealm(new.target)@[[globalThis]].document`) since it occurred to me we probably want to use the realm of the `new`ed constructor, not necessarily of the Element constructor, in the event someone creates a cross-document class hierarchy.

**Comment by annevk** [comment]
In a possible future world we might have "blank" realms where you import features into. In that case you might actually want to get `document` from the same place you got `Element`. Highly theoretical at this point though.
