### ISSUE TITLE
Does HTMLElement need prefix?

### ISSUE THREAD

**Issue by domenic** [domenic/element-constructors#3]
Maybe it is always null. That would simplify things.

If it is always null then we can probably leave prefix and localName separate in Element (see #2) since authors won't be using `new Element` very often and won't have to worry about it when deriving from HTMLElement.

**Comment by annevk** [comment]
It needs one for XHTML, no?

**Comment by domenic** [comment]
Makes sense.

In the new design we use an options object so having `prefix` take up valuable constructor signature space is not a problem.
