### ISSUE TITLE
Node and base URL

### ISSUE THREAD

**Issue by annevk** [domenic/element-constructors#4]
Note that the tentative plan is to move base URL up to the Document class, once `xml:base` is sufficiently killed by @foolip and @bzbarsky et al.

**Comment by foolip** [comment]
I'm waiting for Chrome 40 to reach stable (any time now) to see where the use counter goes:
https://www.chromestatus.com/metrics/feature/timeline/popularity/580

**Comment by annevk** [comment]
Probably not worth fixing further, but I would move the base URL slot to Document so Node no longer needs to derive it at all.
